[package]
name = "dupe-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
jzon = "0.12.5"
sha2 = "0.10.8"
walkdir = "2.5.0"
serde_json = "1.0.133"
serde = { version = "1.0.215", features = ["derive"] }
